#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = ad_device.so
OBJ = 	ad_chan.o ad_dev.o
HDR =	ad_dev.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
