#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = carpal_device.so
OBJ = 	carpal_device.o
HDR =	carpal_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
