#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = touchscreen_device.so
OBJ = 	touchscreen_device.o
HDR =	touchscreen_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
