#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = canusb_device.so
OBJ = 	canusb_device.o
HDR =	canusb_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
