#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = log.so
OBJ = 	log_read.o log_write.o log_channel.o
HDR =	log.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr

