#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = mut3_device.so
OBJ = 	mut3_device.o
HDR =	mut3_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
