#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#
include ../Makefile.hdr

TARGET = apex_device.so
OBJ = 	apex_device.o
HDR =	apex_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
