#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = csv_store.so
OBJ = 	csv_writer.o csv_field.o
HDR =	csv.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
