#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = pi_sys3_device.so
OBJ = 	pi_sys3_device.o
HDR =	pi_sys3_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
