#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = zt2_device.so
OBJ = 	zt2_device.o
HDR =	zt2_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
