#
# Makefile for plugin.
# All functionality can be found in ../Makefile.hdr and ../Makefile.ftr
#

include ../Makefile.hdr

TARGET = lc1_device.so
OBJ = 	lc1_device.o
HDR =	lc1_device.hh $(M1_INCDIR)/component.hh 

include ../Makefile.ftr
